### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [exthmui-legacy/android_packages_apps_GamingMode#2]
error: packages/apps/GamingMode/app/src/main/Android.bp:1:1: module "GamingMode" variant "android_common": sdk_version: sdk_version must have a value when the module is located at vendor or product(only 
if PRODUCT_ENFORCE_PRODUCT_PARTITION_INTERFACE is set).

exthm-11

**Comment by cjybyjk** [comment]
fixed
